/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedReportRouteImport } from './routes/_authenticated/report'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminDeliveriesRouteImport } from './routes/_authenticated/admin.deliveries'
import { Route as AuthenticatedAdminLotsIndexRouteImport } from './routes/_authenticated/admin.lots.index'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminRecallRouteImport } from './routes/_authenticated/admin.recall'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin.staff'
import { Route as AuthenticatedAdminLotsLotIdRouteImport } from './routes/_authenticated/admin.lots.$lotId'
import { Route as AuthenticatedAdminPartnersIndexRouteImport } from './routes/_authenticated/admin.partners.index'
import { Route as AuthenticatedAdminPartnersPartnerIdRouteImport } from './routes/_authenticated/admin.partners.$partnerId'
import { Route as AuthenticatedAdminVenuesIndexRouteImport } from './routes/_authenticated/admin.venues.index'
import { Route as AuthenticatedAdminVenuesVenueIdRouteImport } from './routes/_authenticated/admin.venues.$venueId'
import { Route as ApiPublicV1VenuesRouteImport } from './routes/api/public/v1/venues'
import { Route as ApiPublicV1VenuesSlugRouteImport } from './routes/api/public/v1/venues.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportRoute = AuthenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDeliveriesRoute =
  AuthenticatedAdminDeliveriesRouteImport.update({
    id: '/deliveries',
    path: '/deliveries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLotsIndexRoute =
  AuthenticatedAdminLotsIndexRouteImport.update({
    id: '/lots/',
    path: '/lots/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRecallRoute =
  AuthenticatedAdminRecallRouteImport.update({
    id: '/recall',
    path: '/recall',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLotsLotIdRoute =
  AuthenticatedAdminLotsLotIdRouteImport.update({
    id: '/lots/$lotId',
    path: '/lots/$lotId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPartnersIndexRoute =
  AuthenticatedAdminPartnersIndexRouteImport.update({
    id: '/partners/',
    path: '/partners/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPartnersPartnerIdRoute =
  AuthenticatedAdminPartnersPartnerIdRouteImport.update({
    id: '/partners/$partnerId',
    path: '/partners/$partnerId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVenuesIndexRoute =
  AuthenticatedAdminVenuesIndexRouteImport.update({
    id: '/venues/',
    path: '/venues/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVenuesVenueIdRoute =
  AuthenticatedAdminVenuesVenueIdRouteImport.update({
    id: '/venues/$venueId',
    path: '/venues/$venueId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicV1VenuesRoute = ApiPublicV1VenuesRouteImport.update({
  id: '/api/public/v1/venues',
  path: '/api/public/v1/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1VenuesSlugRoute = ApiPublicV1VenuesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiPublicV1VenuesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/history': typeof AuthenticatedHistoryRoute
  '/report': typeof AuthenticatedReportRoute
  '/admin/deliveries': typeof AuthenticatedAdminDeliveriesRoute
  '/admin/lots/': typeof AuthenticatedAdminLotsIndexRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/recall': typeof AuthenticatedAdminRecallRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/lots/$lotId': typeof AuthenticatedAdminLotsLotIdRoute
  '/admin/partners/$partnerId': typeof AuthenticatedAdminPartnersPartnerIdRoute
  '/admin/venues/$venueId': typeof AuthenticatedAdminVenuesVenueIdRoute
  '/api/public/v1/venues': typeof ApiPublicV1VenuesRouteWithChildren
  '/admin/partners/': typeof AuthenticatedAdminPartnersIndexRoute
  '/admin/venues/': typeof AuthenticatedAdminVenuesIndexRoute
  '/api/public/v1/venues/$slug': typeof ApiPublicV1VenuesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/report': typeof AuthenticatedReportRoute
  '/admin/deliveries': typeof AuthenticatedAdminDeliveriesRoute
  '/admin/lots': typeof AuthenticatedAdminLotsIndexRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/recall': typeof AuthenticatedAdminRecallRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/lots/$lotId': typeof AuthenticatedAdminLotsLotIdRoute
  '/admin/partners/$partnerId': typeof AuthenticatedAdminPartnersPartnerIdRoute
  '/admin/venues/$venueId': typeof AuthenticatedAdminVenuesVenueIdRoute
  '/api/public/v1/venues': typeof ApiPublicV1VenuesRouteWithChildren
  '/admin/partners': typeof AuthenticatedAdminPartnersIndexRoute
  '/admin/venues': typeof AuthenticatedAdminVenuesIndexRoute
  '/api/public/v1/venues/$slug': typeof ApiPublicV1VenuesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/setup': typeof SetupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/report': typeof AuthenticatedReportRoute
  '/_authenticated/admin/deliveries': typeof AuthenticatedAdminDeliveriesRoute
  '/_authenticated/admin/lots/': typeof AuthenticatedAdminLotsIndexRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/recall': typeof AuthenticatedAdminRecallRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/lots/$lotId': typeof AuthenticatedAdminLotsLotIdRoute
  '/_authenticated/admin/partners/$partnerId': typeof AuthenticatedAdminPartnersPartnerIdRoute
  '/_authenticated/admin/venues/$venueId': typeof AuthenticatedAdminVenuesVenueIdRoute
  '/api/public/v1/venues': typeof ApiPublicV1VenuesRouteWithChildren
  '/_authenticated/admin/partners/': typeof AuthenticatedAdminPartnersIndexRoute
  '/_authenticated/admin/venues/': typeof AuthenticatedAdminVenuesIndexRoute
  '/api/public/v1/venues/$slug': typeof ApiPublicV1VenuesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/admin'
    | '/history'
    | '/report'
    | '/admin/deliveries'
    | '/admin/lots/'
    | '/admin/products'
    | '/admin/recall'
    | '/admin/reports'
    | '/admin/staff'
    | '/admin/'
    | '/admin/lots/$lotId'
    | '/admin/partners/$partnerId'
    | '/admin/venues/$venueId'
    | '/api/public/v1/venues'
    | '/admin/partners/'
    | '/admin/venues/'
    | '/api/public/v1/venues/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setup'
    | '/history'
    | '/report'
    | '/admin/deliveries'
    | '/admin/lots'
    | '/admin/products'
    | '/admin/recall'
    | '/admin/reports'
    | '/admin/staff'
    | '/admin'
    | '/admin/lots/$lotId'
    | '/admin/partners/$partnerId'
    | '/admin/venues/$venueId'
    | '/api/public/v1/venues'
    | '/admin/partners'
    | '/admin/venues'
    | '/api/public/v1/venues/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/setup'
    | '/_authenticated/admin'
    | '/_authenticated/history'
    | '/_authenticated/report'
    | '/_authenticated/admin/deliveries'
    | '/_authenticated/admin/lots/'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/recall'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/lots/$lotId'
    | '/_authenticated/admin/partners/$partnerId'
    | '/_authenticated/admin/venues/$venueId'
    | '/api/public/v1/venues'
    | '/_authenticated/admin/partners/'
    | '/_authenticated/admin/venues/'
    | '/api/public/v1/venues/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SetupRoute: typeof SetupRoute
  ApiPublicV1VenuesRoute: typeof ApiPublicV1VenuesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/deliveries': {
      id: '/_authenticated/admin/deliveries'
      path: '/deliveries'
      fullPath: '/admin/deliveries'
      preLoaderRoute: typeof AuthenticatedAdminDeliveriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/lots/': {
      id: '/_authenticated/admin/lots/'
      path: '/lots/'
      fullPath: '/admin/lots/'
      preLoaderRoute: typeof AuthenticatedAdminLotsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/recall': {
      id: '/_authenticated/admin/recall'
      path: '/recall'
      fullPath: '/admin/recall'
      preLoaderRoute: typeof AuthenticatedAdminRecallRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/lots/$lotId': {
      id: '/_authenticated/admin/lots/$lotId'
      path: '/lots/$lotId'
      fullPath: '/admin/lots/$lotId'
      preLoaderRoute: typeof AuthenticatedAdminLotsLotIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/partners/': {
      id: '/_authenticated/admin/partners/'
      path: '/partners'
      fullPath: '/admin/partners/'
      preLoaderRoute: typeof AuthenticatedAdminPartnersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/partners/$partnerId': {
      id: '/_authenticated/admin/partners/$partnerId'
      path: '/partners/$partnerId'
      fullPath: '/admin/partners/$partnerId'
      preLoaderRoute: typeof AuthenticatedAdminPartnersPartnerIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/venues/': {
      id: '/_authenticated/admin/venues/'
      path: '/venues'
      fullPath: '/admin/venues/'
      preLoaderRoute: typeof AuthenticatedAdminVenuesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/venues/$venueId': {
      id: '/_authenticated/admin/venues/$venueId'
      path: '/venues/$venueId'
      fullPath: '/admin/venues/$venueId'
      preLoaderRoute: typeof AuthenticatedAdminVenuesVenueIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/v1/venues': {
      id: '/api/public/v1/venues'
      path: '/api/public/v1/venues'
      fullPath: '/api/public/v1/venues'
      preLoaderRoute: typeof ApiPublicV1VenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/venues/$slug': {
      id: '/api/public/v1/venues/$slug'
      path: '/$slug'
      fullPath: '/api/public/v1/venues/$slug'
      preLoaderRoute: typeof ApiPublicV1VenuesSlugRouteImport
      parentRoute: typeof ApiPublicV1VenuesRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDeliveriesRoute: typeof AuthenticatedAdminDeliveriesRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminRecallRoute: typeof AuthenticatedAdminRecallRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminLotsLotIdRoute: typeof AuthenticatedAdminLotsLotIdRoute
  AuthenticatedAdminPartnersPartnerIdRoute: typeof AuthenticatedAdminPartnersPartnerIdRoute
  AuthenticatedAdminVenuesVenueIdRoute: typeof AuthenticatedAdminVenuesVenueIdRoute
  AuthenticatedAdminLotsIndexRoute: typeof AuthenticatedAdminLotsIndexRoute
  AuthenticatedAdminPartnersIndexRoute: typeof AuthenticatedAdminPartnersIndexRoute
  AuthenticatedAdminVenuesIndexRoute: typeof AuthenticatedAdminVenuesIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDeliveriesRoute: AuthenticatedAdminDeliveriesRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminRecallRoute: AuthenticatedAdminRecallRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminLotsLotIdRoute: AuthenticatedAdminLotsLotIdRoute,
  AuthenticatedAdminPartnersPartnerIdRoute:
    AuthenticatedAdminPartnersPartnerIdRoute,
  AuthenticatedAdminVenuesVenueIdRoute: AuthenticatedAdminVenuesVenueIdRoute,
  AuthenticatedAdminLotsIndexRoute: AuthenticatedAdminLotsIndexRoute,
  AuthenticatedAdminPartnersIndexRoute: AuthenticatedAdminPartnersIndexRoute,
  AuthenticatedAdminVenuesIndexRoute: AuthenticatedAdminVenuesIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedReportRoute: AuthenticatedReportRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicV1VenuesRouteChildren {
  ApiPublicV1VenuesSlugRoute: typeof ApiPublicV1VenuesSlugRoute
}

const ApiPublicV1VenuesRouteChildren: ApiPublicV1VenuesRouteChildren = {
  ApiPublicV1VenuesSlugRoute: ApiPublicV1VenuesSlugRoute,
}

const ApiPublicV1VenuesRouteWithChildren =
  ApiPublicV1VenuesRoute._addFileChildren(ApiPublicV1VenuesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SetupRoute: SetupRoute,
  ApiPublicV1VenuesRoute: ApiPublicV1VenuesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
